export const onBoardingData = [
  {
    id: 'nickname',
    title: '영어이름을 알려주세요',
    subTitle: '만나서 반가워요. 여러분을 뭐라고 부르면 될까요?',
    placeHolder: 'Jason',
    next: 'birthday',
  },
  {
    id: 'birthday',
    title: '여러분의 생일을 알려주세요.',
    subTitle: '멋진 이름이에요! 환영해요.',
    placeHolder: 'YYYY-MM-DD',
    next: 'phone-number',
  },
  {
    id: 'phone-number',
    title: '전화번호를 알려주세요',
    subTitle: '야호~! 이제 Slack에서 생일을 축하해드릴게요.',
    placeHolder: '010-0000-0000',
    next: 'major',
  },
  {
    id: 'major',
    title: '전공을 알려주세요:)',
    subTitle: '알려주셔서 감사해요!',
    placeHolder: '구글개발학과 무슨전공',
    next: 'student-id',
  },
  {
    id: 'student-id',
    title: '학번을 알려주세요',
    subTitle: '멋진 전공이네요!',
    placeHolder: '20211234',
    next: 'github',
  },
  {
    id: 'github',
    title: '깃허브에 사용 중인 이메일을 알려주세요',
    subTitle: '우와! 감사해요. 거의 다 했어요.',
    placeHolder: 'gdscdju@gmail.com',
    next: 'message',
  },
  {
    id: 'message',
    title: '한 줄 소개글을 작성해주세요.',
    subTitle: '마지막으로 여러분을 소개해주세요.',
    placeHolder: '60자 이내로 작성해주세요.',
    next: 'ticket',
  },
];
