export const memberList = [
  {
    nickname: 'Peony',
    name: '정명주',
    role: 'Lead',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TWSK3RQU-a3e79f8f5148-512',
    text: '이 구역의 짱은 나야!',
    position: 'Backend',
  },

  {
    nickname: 'Soopeach',
    name: '전현수',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U7QRL4SC-6e454afca9f4-512',
    text: '',
    position: 'Android',
  },
  {
    nickname: 'Iden',
    name: '이지훈',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04180XL4V7-6da93e855eaa-512',
    text: '',
    position: 'iOS',
  },
  {
    nickname: 'Jayden',
    name: '옥지훈',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04K8FKSNMS-d5754e45d6b5-512',
    text: '',
    position: 'Frontend',
  },
  {
    nickname: 'Pascal',
    name: 'Kane Ki Hayashi',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02C9FTGT7H-370ce27dc622-512',
    text: '',
    position: 'Machine Learning',
  },
  {
    nickname: 'Lucy',
    name: '박진혜',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CH3YMBE2-bf3052404c23-512',
    text: '',
    position: 'Frontend',
  },
  {
    nickname: 'Jade',
    name: 'Jeongu Seo',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CPD32N3D-g0beff217a80-512',
    text: '',
    position: 'Android',
  },
  {
    nickname: 'Lala',
    name: 'Lala',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02D2RXTP3K-5b98e49b6beb-512',
    text: '',
    position: 'Machine Learning',
  },
  {
    nickname: 'Nox',
    name: '전상민',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TLNR15PE-b14a81ec08cb-512',
    text: '',
    position: 'Backend',
  },

  {
    nickname: 'PuRang',
    name: '손민성',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U030E9L5VB8-d202c97a72ac-512',
    text: '',
    position: 'Android',
  },
  {
    nickname: 'Winnie',
    name: '유미소',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U031VV8SS6R-gea0879bc69f-512',
    text: '',
    position: 'Designer',
  },
  {
    nickname: 'Dawn',
    name: '원동규',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U040TCMFASF-af2ea49a5ff7-512',
    text: '',
    position: 'Backend',
  },

  {
    nickname: 'Ace',
    name: '김경하',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U040W6PS0TW-g2d312e41758-512',
    text: '',
    position: 'Android',
  },

  {
    nickname: 'Ayaan',
    name: '장규진',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U041JBLSY8Y-8d1677399cb0-512',
    text: '',
    position: 'Machine Learning',
  },
  {
    nickname: 'Aqua',
    name: '이우민',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04JNJQQX2T-b29abe9da45f-512',
    text: '',
    position: 'Frontend',
  },
  {
    nickname: 'Louis',
    name: 'Louis',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04K26UEZMK-9d9eac3bfcdc-512',
    text: '',
    position: 'Backend',
  },
  {
    nickname: 'James',
    name: '정우성',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04K6G3JDDJ-84b11f3a8439-512',
    text: '',
    position: 'Frontend',
  },
  {
    nickname: 'Donny',
    name: '조현돈',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U04K6VC2WR1-dc678dfd3d31-512',
    text: '',
    position: 'Frontend',
  },

  {
    nickname: 'Judy',
    name: '김정하',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U052X10G0SZ-g2ffb49c81e1-512',
    text: '',
    position: 'Designer',
  },
  //   {
  //     nickname: 'Mini',
  //     name: '오소영',
  //     role: 'Member',
  //     image: 'https://ca.slack-edge.com/T02BE2ERU5A-U040TP38YUA-0317ab883a84-512',
  //     text: '',
  //     position: 'Frontend',
  //   },
  //   {
  //     nickname: 'Panda',
  //     name: '강민호',
  //     role: 'Member',
  //     image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U0C94L1X-184728f37ca1-512',
  //     text: '',
  //     position: 'Backend',
  //   },
  //   {
  //     nickname: 'Cindy',
  //     name: '박수현',
  //     role: 'Core Member',
  //     image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TMHKQJQ6-a88706484b95-512',
  //     text: '',
  //     position: 'Designer',
  //   },
  // {
  //     nickname: "Rulu",
  //     name: "김수진",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02CWDN14CU-a7abf33eadfd-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Als",
  //     name: "신상민",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U040LUD1CG6-1558de05b20e-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Jason",
  //     name: "정준혁",
  //     role: "Member",
  //     image: "https: //ca.slack-edge.com/T02BE2ERU5A-U02B4R8P8HK-d049523078ea-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Harry",
  //     name: "Hyun Ki Park",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02BR888JMT-6895fc3ca3f5-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Reese",
  //     name: "안주원",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02CH2LV8VC-b961b9ccc504-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Glenn",
  //     name: "Seung Woo Jung",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U040W4HRMEY-6f00bba63c01-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Blaire",
  //     name: "이소희",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02TWS2TDS5-cbb48b945dba-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Want",
  //     name: "Want",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02CH6KQT8Q-45a696d9961d-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Jim",
  //     name: "전병선",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U02TKATKRBN-5c528ec281ec-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //     nickname: "Gunzo",
  //     name: "권소윤",
  //     role: "Member",
  //     image: "https://ca.slack-edge.com/T02BE2ERU5A-U030NT7MP2Q-966fdd0bcd88-512",
  //     text: "",
  //     position: ""
  // },
  // {
  //   nickname: 'Gabi	',
  //   name: '신동석',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CPF84WSX-cb49cf16f436-512',
  //   text: '王자 만들고 싶다',
  //   position: 'Frontend',
  // },
  // {
  //   nickname: 'Samjong',
  //   name: '김지훈',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02D2S7GQN5-c24df3df3cea-512',
  //   text: '더 나은 미래',
  //   position: 'Backend',
  // },
  // {
  //   nickname: 'Toby	',
  //   name: '황지영',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CM3382ER-41670417f48d-512',
  //   text: '왜요? 제가 INFP처럼 보이나요?',
  //   position: 'Android',
  // },
  // {
  //   nickname: 'Jimmy',
  //   name: '강지명',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02C955NKF1-a4f02af91966-512',
  //   text: '약은 약사에게, 역학은 지미에게',
  //   position: 'Android',
  // },
  // {
  //   nickname: 'Marine	',
  //   name: '권승민',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U886HJPJ-7ed32c3d38b6-512',
  //   text: '해병 출신 아닙니다..',
  //   position: 'Backend',
  // },
  //
  // {
  //   nickname: 'Hazel	',
  //   name: '박해주',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TC3GCYDC-7655c573f14a-512',
  //   text: '나는 으른이다.. 게으른..',
  //   position: 'Designer',
  // },
  //
  // {
  //   nickname: 'DD',
  //   name: '나도희',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TJH9V38V-b7bf85d0d373-512',
  //   text: '겸손의 미덕',
  //   position: 'Beginner',
  // },
  // {
  //   nickname: 'Ben',
  //   name: '신성용',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U8SJ1TPB-8e4cb047dab2-512',
  //   text: '준비됐지,몸? 아니 아직, 뇌',
  //   position: 'Beginner',
  // },
  // {
  //   nickname: 'Jay',
  //   name: '안정은',
  //   role: 'Member',
  //   image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02UNEQAFFA-g8f794d1bd8e-512',
  //   text: '무슨 생각을 해… 그냥 하는거지…',
  //   position: 'Beginner',
  // },
];
