---
title: props
---
<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

## className

컴포넌트의 root element(`div`)에 추가되는 className입니다.

Type: [string][1]

## hasError

에러 상태를 표시합니다.

Type: [boolean][2]

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String

[2]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean
