export const memberList = [
  {
    nickname: 'Jason',
    name: '정준혁',
    role: 'Lead',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02B4R8P8HK-bdf04fe4ad6b-512',
    text: '리액트에 미친 사람입니다',
    position: 'Frontend',
  },
  {
    nickname: 'Harry',
    name: '박현기',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02BR888JMT-dd70b40bca94-512',
    text: '엄마 나 여기있어',
    position: 'Android',
  },
  {
    nickname: 'Want',
    name: '정소연',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CH6KQT8Q-a03a44566103-512',
    text: '빛나지만 눈부시지 않게',
    position: 'Backend',
  },
  {
    nickname: 'Blaire	',
    name: '이소희',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TWS2TDS5-726b69e0e1c8-512',
    text: '생기가 없다면 먹을 걸 주세요',
    position: 'Designer',
  },
  {
    nickname: 'Samjong',
    name: '김지훈',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02D2S7GQN5-c24df3df3cea-512',
    text: '더 나은 미래',
    position: 'Backend',
  },
  {
    nickname: 'Rocoli',
    name: '유형찬',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02C8B72LT1-e35fe9b38122-512',
    text: '내 죽음이 내 삶 보다 가취가 있기를',
    position: 'Backend',
  },
  {
    nickname: 'Jim',
    name: '전병선',
    role: 'Core Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TKATKRBN-f7b7e7e1dc15-512',
    text: '돈 많은 백수가 꿈이에요',
    position: 'Android',
  },
  {
    nickname: 'Reese',
    name: '안주원',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CH2LV8VC-efb0ce60230f-512',
    text: '개미는 오늘도 열심히 일을 하네',
    position: 'Backend',
  },
  {
    nickname: 'Lulu',
    name: '김수진',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CWDN14CU-557c4fe53e5e-512',
    text: '룰루하게 살아보아요 ^&^',
    position: 'Frontend',
  },
  {
    nickname: 'Jade	',
    name: '서정우',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CPD32N3D-6b7a165e5bb6-512',
    text: '낮밤 언제 바꾸지...',
    position: 'Frontend',
  },
  {
    nickname: 'Gabi	',
    name: '신동석',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CPF84WSX-cb49cf16f436-512',
    text: '王자 만들고 싶다',
    position: 'Frontend',
  },

  {
    nickname: 'Toby	',
    name: '황지영',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CM3382ER-41670417f48d-512',
    text: '왜요? 제가 INFP처럼 보이나요?',
    position: 'Android',
  },
  {
    nickname: 'Jimmy',
    name: '강지명',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02C955NKF1-a4f02af91966-512',
    text: '약은 약사에게, 역학은 지미에게',
    position: 'Android',
  },

  {
    nickname: 'Pascal',
    name: '임종수',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02C9FTGT7H-6573ad607286-512',
    text: '복잡한 걸 좋아하는 사람은 없다',
    position: 'Beginner',
  },
  {
    nickname: 'Lala	',
    name: '라허운',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02D2RXTP3K-5b98e49b6beb-512',
    text: 'ㅅ..살려주세요..자고싶어요....',
    position: 'Beginner',
  },
  {
    nickname: 'Lucy	',
    name: '박진혜',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02CH3YMBE2-03395b575cae-512',
    text: '저는 아무고토 몰라요..',
    position: 'Beginner',
  },
  {
    nickname: 'Marine	',
    name: '권승민',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U886HJPJ-7ed32c3d38b6-512',
    text: '해병 출신 아닙니다..',
    position: 'Backend',
  },
  {
    nickname: 'Panda	',
    name: '강민호',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U0C94L1X-ad7ea4fc4fb7-512',
    text: '실력 좋은 개발자가 되고싶어여~~',
    position: 'Backend',
  },
  {
    nickname: 'Peony	',
    name: '정명주',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TWSK3RQU-a3e79f8f5148-512',
    text: '응애개발자',
    position: 'Backend',
  },
  {
    nickname: 'Chois',
    name: '최병주',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02T78C2U07-16c618db6e0b-512',
    text: '우리 모두 성공 기원',
    position: 'Frontend',
  },
  {
    nickname: 'Chaz',
    name: '문희리',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02T3GSSBRV-55acf03d8b77-512',
    text: '재즈 아니고 차즈 아니고 채즈네',
    position: 'Frontend',
  },

  {
    nickname: 'Purang',
    name: '손민성',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U030E9L5VB8-f08e7737022b-512',
    text: '내일은 오늘보다 더 좋은 날 되길',
    position: 'Android',
  },
  {
    nickname: 'Hazel	',
    name: '박해주',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TC3GCYDC-7655c573f14a-512',
    text: '나는 으른이다.. 게으른..',
    position: 'Designer',
  },
  {
    nickname: 'Cindy',
    name: '박수현',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TMHKQJQ6-6f56b34c34c9-512',
    text: '강하지?강하지! 우리집 강아지는 복슬강아지',
    position: 'Designer',
  },
  {
    nickname: 'Gunzo',
    name: '권소윤',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U030NT7MP2Q-ea60c5fb2098-512',
    text: '웹디자인사우르스',
    position: 'Designer',
  },
  {
    nickname: 'Winnie',
    name: '유미소',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U031VV8SS6R-gea0879bc69f-512',
    text: '안녕하세용?',
    position: 'Designer',
  },
  {
    nickname: 'Soopeach	',
    name: '전현수',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U7QRL4SC-ac441340652f-512',
    text: '같이...가요...',
    position: 'Beginner',
  },
  {
    nickname: 'Nox',
    name: '전상민',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TLNR15PE-g17d802fcdd7-512',
    text: '게으르기 위해 노력하자',
    position: 'Beginner',
  },
  {
    nickname: 'DD',
    name: '나도희',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02TJH9V38V-b7bf85d0d373-512',
    text: '겸손의 미덕',
    position: 'Beginner',
  },
  {
    nickname: 'Ben',
    name: '신성용',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02U8SJ1TPB-8e4cb047dab2-512',
    text: '준비됐지,몸? 아니 아직, 뇌',
    position: 'Beginner',
  },
  {
    nickname: 'Jay',
    name: '안정은',
    role: 'Member',
    image: 'https://ca.slack-edge.com/T02BE2ERU5A-U02UNEQAFFA-g8f794d1bd8e-512',
    text: '무슨 생각을 해… 그냥 하는거지…',
    position: 'Beginner',
  },
];
