name: '@gdsc-dju/gds-styles Package Publish'

on:
  push:
    paths:
      - "packages/styles/**"
      - ".github/workflows/gds-style-publish.yml"
jobs:
  gds-ui-publish-npm:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/styles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: version up
        run: |
          git pull
          git config --global user.name 'hyeoke0'
          git config --global user.email jhjeong00@gmail.com
          yarn release
          git push --follow-tags
        working-directory: ${{ env.working-directory }}
      - run: npm publish
        working-directory: ${{ env.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}