name: Deploy to GDSC DJU WEB Live Channel

on:
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
      - ".github/workflows/gdsc-dju-web-deploy-live.yml"
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - "apps/web/**"
      - ".github/workflows/gdsc-dju-web-deploy-live.yml"
jobs:
  Deploy_Live_channel:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      working-directory: ./apps/web
    environment:
      name: GDSC DJU WEB Production
      url: https://gdscdju.dev/
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 캐시 폴더를 가져오고 있어요.
        id: yarn-cache-dir-path
        run: echo "dir=$(cd client && yarn config get cacheFolder)" >> $GITHUB_ENV

      - name: 캐시 의존성을 설정하고 있어요.
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Node 버전/캐싱여부를 설정하고 있어요.
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./yarn.lock
          registry-url: "https://registry.yarnpkg.com"
      - name: Setting .env
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APPID=${{ secrets.VITE_FIREBASE_APPID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          cat .env
        working-directory: ${{ env.working-directory }}
      - name: install package
        run: yarn install
      - name: Project Build
        run: yarn turbo run build --filter=@gdsc-dju/web
      - uses: HyeokE/action-hosting-deploy@main
        id: run_firebase_deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          channelId: live
          projectId: gdsc-dju
          entryPoint: ${{ env.working-directory }}
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_FRONT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_FRONT_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-web has been deployed to Live channel
            `Contributor` ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` https://web.gdscdju.dev
            `Build Time` ${{steps.run_firebase_deploy.outputs.expire_time}}
